"""Generate complete, canonical API pages and fail builds on missing entries.

AST discovery avoids importing download clients or exposing config values during
discovery. Autodoc imports definitions, but never calls qlib.init or native DLLs.
"""

import ast
import json
from pathlib import Path

from sphinx.util import logging

LOGGER = logging.getLogger(__name__)
FUNCTIONS = (ast.FunctionDef, ast.AsyncFunctionDef)
MARKER = ".. Generated by api_reference; do not edit."


def _write(path, content):
    path.parent.mkdir(parents=True, exist_ok=True)
    if not path.exists() or path.read_text(encoding="utf-8") != content:
        path.write_text(content, encoding="utf-8")


def generate(app):
    root = Path(app.confdir).parent
    destination = Path(app.srcdir) / "_generated"
    sections = {"qlib": [], "scripts": []}
    expected = []
    generated = set()
    for package in sections:
        for path in sorted((root / package).rglob("*.py")):
            tree = ast.parse(path.read_text(encoding="utf-8"))
            definitions = [node for node in tree.body if isinstance(node, (*FUNCTIONS, ast.ClassDef))]
            if not definitions:
                continue  # Re-export packages are described in the API landing page.
            parts = list(path.relative_to(root).with_suffix("").parts)
            if parts[-1] == "__init__":
                parts.pop()
            module = ".".join(parts)
            sections[package].append(module)
            page = [MARKER, "", module, "=" * len(module), "", f".. automodule:: {module}", ""]
            for private, heading in ((False, "函数与类"), (True, "内部实现参考")):
                selected = [node for node in definitions if node.name.startswith("_") == private]
                if not selected:
                    continue
                page += [heading, "-" * 30, ""]
                if private:
                    page += ["下列下划线接口供实现维护和调试使用。", ""]
                for node in selected:
                    name = f"{module}.{node.name}"
                    expected.append(name)
                    if isinstance(node, FUNCTIONS):
                        page += [f".. autofunction:: {name}", ""]
                    else:
                        methods = [item.name for item in node.body if isinstance(item, FUNCTIONS)]
                        expected.extend(f"{name}.{method}" for method in methods)
                        specials = sorted({"__init__", *(m for m in methods if m.startswith("__"))})
                        page += [f".. autoclass:: {name}", "   :members:", "   :undoc-members:",
                                 "   :private-members:", f"   :special-members: {', '.join(specials)}", ""]
            output = destination / f"{module}.rst"
            generated.add(output)
            _write(output, "\n".join(page))
    for package, modules in sections.items():
        title = "Python 包 API" if package == "qlib" else "下载与构建脚本 API"
        lines = [MARKER, "", title, "=" * 40, "", "由源码自动生成，包含已定义的函数、类、方法及内部辅助接口。", "",
                 ".. toctree::", "   :maxdepth: 1", ""]
        lines += [f"   {module}" for module in modules]
        output = destination / f"{package}_index.rst"
        generated.add(output)
        _write(output, "\n".join(lines) + "\n")
    for path in destination.glob("*.rst"):
        if path not in generated and path.read_text(encoding="utf-8").startswith(MARKER):
            path.unlink()
    app._api_expected = expected
    LOGGER.info("API discovery: %s functions/classes/methods in %s modules", len(expected), sum(map(len, sections.values())))


def verify(app, exception):
    if exception is not None:
        return
    documented = {item[0] for item in app.env.domains["py"].get_objects()}
    expected = app._api_expected
    missing = sorted(set(expected) - documented)
    report = {"expected_count": len(expected), "documented_count": len(set(expected) & documented),
              "missing": missing, "objects": sorted(expected)}
    Path(app.outdir, "api-coverage.json").write_text(json.dumps(report, ensure_ascii=False, indent=2), encoding="utf-8")
    for name in missing:
        LOGGER.warning("API object is missing from the documentation: %s", name)
    LOGGER.info("API coverage: %s/%s objects documented", report["documented_count"], report["expected_count"])


def setup(app):
    app.connect("builder-inited", generate)
    app.connect("build-finished", verify)
    return {"version": "1.0", "parallel_read_safe": True, "parallel_write_safe": True}
